### ISSUE TITLE
Project roadmap

### ISSUE THREAD

**Issue by jstolarek** [jstolarek/liveness-slicing#4]
A TODO list for the project. This ticket is a moving target.

# Short-term

  * [x] delete redundant bwd slicing files
  * [x] write examples for bwd slicing
  * [x] bwd slicing almost certainly has a bug. When reconstructing a numeric literal its value should be taken from a trace, not from the slicing criterion. Otherwise if we have (3 + 4) || 7 and we slice 7 w.r.t. 7 we will get (7 + 7), not (3 + 4)
  * [x] fix admitted proofs in ImpState
  * [x] amend monotonicity proof for forward slicing
  * [x] prove left and right consistency of forward and backward slicing
  * [x] write monotonicity proof for bwd slicing
  * [x] write Galois connection proof for fwd and bwd

# Long-term Roadmap

  * [x] write liveness analysis for arithmetic expressions and proof its relationship to slicing

  * [x] do the same for boolean expressions

  * [x] do the same for commands.  This might require annotated holes - see #3
